"""feat: final... maybe

Revision ID: 93c9c3ebe209
Revises: b24f68bce677
Create Date: 2026-07-01 04:01:27.421069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '93c9c3ebe209'
down_revision: Union[str, Sequence[str], None] = 'b24f68bce677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_giveaway_participants')
    op.drop_table('giveaways')
    op.drop_table('tg_users')
    op.drop_table('tg_giveaways')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('tg_giveaways',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator_telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('channel_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('channel_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('channel_username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('announcement_message', sa.TEXT(), nullable=False),
    sa.Column('button_color', sa.VARCHAR(length=32), nullable=False),
    sa.Column('prize_places', sa.INTEGER(), nullable=False),
    sa.Column('starts_at', sa.DATETIME(), nullable=False),
    sa.Column('ends_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('winner_ids', sqlite.JSON(), nullable=True),
    sa.Column('winner_snapshots', sqlite.JSON(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creator_telegram_id'], ['tg_users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_users',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_file_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('giveaways',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('prizes_amount', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_datetime', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_giveaway_participants',
    sa.Column('giveaway_id', sa.INTEGER(), nullable=False),
    sa.Column('user_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['tg_giveaways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['tg_users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('giveaway_id', 'user_telegram_id')
    )
    # ### end Alembic commands ###
