"""fix: no useless columns

Revision ID: b24f68bce677
Revises: 08ba283f497b
Create Date: 2026-06-30 19:45:49.794700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24f68bce677'
down_revision: Union[str, Sequence[str], None] = '08ba283f497b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('end_datetime', sa.DateTime(), nullable=False))
    op.drop_column('giveaways', 'end_date')
    op.drop_column('giveaways', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('end_time', sa.TIME(), nullable=False))
    op.add_column('giveaways', sa.Column('end_date', sa.DATE(), nullable=False))
    op.drop_column('giveaways', 'end_datetime')
    # ### end Alembic commands ###
